#ifndef CELAYER_CE_API_H
#define CELAYER_CE_API_H

enum {
    CE_MODULE_INTERNAL = 0,
    CE_MODULE_COREDLL = 1,
    CE_MODULE_AYGSHELL,
    CE_MODULE_COMMCTRL,
    CE_MODULE_COMMDLG,
    CE_MODULE_WINSOCK,
    CE_MODULE_OLE32
};

enum {
    CE_API_GET_LAST_ERROR = 1, CE_API_SET_LAST_ERROR, CE_API_GET_TICK_COUNT,
    CE_API_VIRTUAL_ALLOC, CE_API_VIRTUAL_FREE, CE_API_CLOSE_HANDLE,
    CE_API_CREATE_FILE_W, CE_API_READ_FILE, CE_API_WRITE_FILE, CE_API_SET_FILE_POINTER,
    CE_API_CREATE_EVENT_W, CE_API_SET_EVENT, CE_API_RESET_EVENT,
    CE_API_POST_MESSAGE_W, CE_API_GET_MESSAGE_W, CE_API_CREATE_WINDOW_EX_W,
    CE_API_DESTROY_WINDOW, CE_API_SHOW_WINDOW, CE_API_INVALIDATE_RECT, CE_API_EXIT_PROCESS,
    CE_API_SLEEP, CE_API_GET_SYSTEM_TIME, CE_API_GET_LOCAL_TIME,
    CE_API_CREATE_DIRECTORY_W, CE_API_REMOVE_DIRECTORY_W, CE_API_DELETE_FILE_W,
    CE_API_MOVE_FILE_W, CE_API_GET_FILE_ATTRIBUTES_W, CE_API_GET_FILE_SIZE,
    CE_API_FLUSH_FILE_BUFFERS, CE_API_VIRTUAL_PROTECT, CE_API_LSTRLEN_W,
    CE_API_MEMCPY, CE_API_MEMSET, CE_API_LSTRCPY_W, CE_API_PEEK_MESSAGE_W,
    CE_API_REGISTER_CLASS_W, CE_API_GET_CLIENT_RECT, CE_API_GET_DC, CE_API_RELEASE_DC,
    CE_API_CREATE_SOLID_BRUSH, CE_API_DELETE_OBJECT, CE_API_FILL_RECT, CE_API_SET_PIXEL,
    CE_API_DEF_WINDOW_PROC_W, CE_API_TRANSLATE_MESSAGE, CE_API_DISPATCH_MESSAGE_W,
    CE_API_REG_CREATE_KEY_EX_W, CE_API_REG_OPEN_KEY_EX_W, CE_API_REG_CLOSE_KEY,
    CE_API_REG_SET_VALUE_EX_W, CE_API_REG_QUERY_VALUE_EX_W, CE_API_REG_DELETE_VALUE_W,
    CE_API_TEXT_OUT_W, CE_API_DRAW_TEXT_W, CE_API_SET_TEXT_COLOR,
    CE_API_SET_BK_COLOR, CE_API_SET_BK_MODE, CE_API_FIND_FIRST_FILE_W,
    CE_API_FIND_NEXT_FILE_W, CE_API_FIND_CLOSE, CE_API_LOAD_LIBRARY_W,
    CE_API_FREE_LIBRARY, CE_API_GET_PROC_ADDRESS, CE_API_GET_MODULE_HANDLE_W,
    CE_API_TLS_CALL, CE_API_TLS_ALLOC, CE_API_TLS_FREE, CE_API_TLS_GET_VALUE,
    CE_API_TLS_SET_VALUE, CE_API_OUTPUT_DEBUG_STRING_W, CE_API_BEGIN_PAINT,
    CE_API_END_PAINT, CE_API_GET_STOCK_OBJECT, CE_API_SELECT_OBJECT,
    CE_API_CREATE_PEN, CE_API_RECTANGLE, CE_API_MOVE_TO_EX, CE_API_LINE_TO,
    CE_API_SET_TIMER, CE_API_KILL_TIMER, CE_API_GET_KEY_STATE,
    CE_API_GET_ASYNC_KEY_STATE, CE_API_GET_SYSTEM_METRICS, CE_API_GET_DEVICE_CAPS,
    CE_API_MESSAGE_BOX_W, CE_API_LOAD_STRING_W, CE_API_GET_SYSTEM_INFO
};

#define CE_INTERNAL_RETURN_WNDPROC 1
#define CE_INTERNAL_RETURN_DLL 2
#define CE_API_TRAP_ADDRESS(module, function) \
    (0xee000000u | ((unsigned)(module) << 18) | ((unsigned)(function) << 2))
#define CE_TRAP_NATIVE UINT32_C(0x80000000)
#define CE_TRAP_SOFTWARE_INTERRUPT UINT32_C(0x40000000)

enum { CE_AYG_SH_INIT_DIALOG = 1, CE_AYG_SH_CREATE_MENU_BAR, CE_AYG_SH_FULL_SCREEN,
       CE_AYG_SH_DONE_BUTTON, CE_AYG_SH_SIP_PREFERENCE,
       CE_AYG_SH_HANDLE_WM_ACTIVATE, CE_AYG_SH_HANDLE_WM_SETTING_CHANGE };
enum { CE_COMMCTRL_INIT_COMMON_CONTROLS = 1, CE_COMMCTRL_INIT_COMMON_CONTROLS_EX };
enum { CE_OLE_CO_INITIALIZE_EX = 1, CE_OLE_CO_UNINITIALIZE };

#endif
